/*
 * generated by Xtext 2.31.0
 */
package org.xtext.project.cw;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
