/**
 * generated by Xtext 2.31.0
 */
package org.xtext.project.cw.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.cw.myDsl.Model#getEntities <em>Entities</em>}</li>
 *   <li>{@link org.xtext.project.cw.myDsl.Model#getScreens <em>Screens</em>}</li>
 *   <li>{@link org.xtext.project.cw.myDsl.Model#getStartScreen <em>Start Screen</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.cw.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.project.cw.myDsl.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see org.xtext.project.cw.myDsl.MyDslPackage#getModel_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Screens</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.project.cw.myDsl.Screen}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Screens</em>' containment reference list.
   * @see org.xtext.project.cw.myDsl.MyDslPackage#getModel_Screens()
   * @model containment="true"
   * @generated
   */
  EList<Screen> getScreens();

  /**
   * Returns the value of the '<em><b>Start Screen</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Screen</em>' reference.
   * @see #setStartScreen(Screen)
   * @see org.xtext.project.cw.myDsl.MyDslPackage#getModel_StartScreen()
   * @model
   * @generated
   */
  Screen getStartScreen();

  /**
   * Sets the value of the '{@link org.xtext.project.cw.myDsl.Model#getStartScreen <em>Start Screen</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Screen</em>' reference.
   * @see #getStartScreen()
   * @generated
   */
  void setStartScreen(Screen value);

} // Model
