/**
 * generated by Xtext 2.31.0
 */
package org.xtext.project.cw.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Screen</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.cw.myDsl.Screen#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.project.cw.myDsl.Screen#getEntity <em>Entity</em>}</li>
 *   <li>{@link org.xtext.project.cw.myDsl.Screen#getTriggers <em>Triggers</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.cw.myDsl.MyDslPackage#getScreen()
 * @model
 * @generated
 */
public interface Screen extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.project.cw.myDsl.MyDslPackage#getScreen_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.project.cw.myDsl.Screen#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference.
   * @see #setEntity(Entity)
   * @see org.xtext.project.cw.myDsl.MyDslPackage#getScreen_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link org.xtext.project.cw.myDsl.Screen#getEntity <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Triggers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.project.cw.myDsl.Trigger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triggers</em>' containment reference list.
   * @see org.xtext.project.cw.myDsl.MyDslPackage#getScreen_Triggers()
   * @model containment="true"
   * @generated
   */
  EList<Trigger> getTriggers();

} // Screen
