/**
 * generated by Xtext 2.31.0
 */
package org.xtext.project.cw.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.cw.myDsl.Trigger#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link org.xtext.project.cw.myDsl.Trigger#getScreen <em>Screen</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.cw.myDsl.MyDslPackage#getTrigger()
 * @model
 * @generated
 */
public interface Trigger extends EObject
{
  /**
   * Returns the value of the '<em><b>Trigger</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' attribute.
   * @see #setTrigger(String)
   * @see org.xtext.project.cw.myDsl.MyDslPackage#getTrigger_Trigger()
   * @model
   * @generated
   */
  String getTrigger();

  /**
   * Sets the value of the '{@link org.xtext.project.cw.myDsl.Trigger#getTrigger <em>Trigger</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger</em>' attribute.
   * @see #getTrigger()
   * @generated
   */
  void setTrigger(String value);

  /**
   * Returns the value of the '<em><b>Screen</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Screen</em>' reference.
   * @see #setScreen(Screen)
   * @see org.xtext.project.cw.myDsl.MyDslPackage#getTrigger_Screen()
   * @model
   * @generated
   */
  Screen getScreen();

  /**
   * Sets the value of the '{@link org.xtext.project.cw.myDsl.Trigger#getScreen <em>Screen</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Screen</em>' reference.
   * @see #getScreen()
   * @generated
   */
  void setScreen(Screen value);

} // Trigger
