/*
 * generated by Xtext 2.31.0
 */
package org.xtext.project.cw.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
